# This is a basic workflow to help you get started with Actions

name: Generate Firmwares

# Controls when the workflow will run
on:
  push:
  # schedule:
  #  - cron: "0 12 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup and Build
        continue-on-error: true
        run: |
          pip install milc
          python3 -m pip install --user qmk
          qmk setup -y
          for t in keebio/iris/rev7 ferris/sweep;
            do echo "Building QMK for $t";
            qmk compile -j 2 -kb $t -km manna-harbour_miryoku -e MIRYOKU_ALPHAS=COLEMAKDH
          done
          find ~/work/miryoku_qmk/miryoku_qmk -maxdepth 1 -name "*.hex"
          mkdir -p ~/compiled/firmware
          find ~/work/miryoku_qmk/miryoku_qmk -maxdepth 1 -name "*.hex" -exec mv -v '{}' ~/compiled/firmware \;


      - name: Set Release Date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Create GitHub release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{env.RELEASE_DATE}}"
          title: ${{ env.ReleaseVersion }}
          prerelease: false
          files: |
            /home/runner/compiled/firmware/*.hex
